# some more ls aliases
alias ll='ls -alF'
alias la='ls -la'
alias l='ls -CF'

# custom aliases
alias die_mothafucka='sudo shutdown now'
alias gopy_output='xclip -selection clipboard'
alias asd='source ~/.bashrc && source ~/px4_firm_source.sh && roslaunch drone_gazebo april_tags_mania.launch'
alias asda='source ~/.bashrc && source ~/apm_sitl_source.sh && roslaunch drone_gazebo april_tags_mania_apm.launch'
alias dfg='roslaunch drone_bringup gazebo_bringup.launch'
alias dfga='roslaunch drone_bringup gazebo_bringup_apm.launch'
alias qtcc='qtcreator-ros -client'
alias sob='source ~/.bashrc'
alias nabrc_n_m='nano ~/.bashrc'
alias catbashrc='colorcat ~/.bashrc'
alias adamim_ardu_tasakli='sim_vehicle.py -N -v ArduCopter -f gazebo-iris -m --mav10 -I0 -l 40.8796573,29.4100675,0,0'
alias vf='echo "Running cd for alias vf" && cd'
alias colorcat='pygmentize -g'
export EDITOR='nano -c'
export ROSCONSOLE_FORMAT='${message}
alias nan='nano -c'
alias gopy_output='xclip -selection clipboard'
alias gti='git'
export EDITOR='nano -c'
export ROSCONSOLE_FORMAT='${node}: ${message}'
